version: '3'

env:
  CHART_NAME: query-exporter
  CHART_PATH: query-exporter
  GITHUB_REPO: query-exporter

tasks:
  commitlint:
    desc: run commitlint
    cmds:
      - npx commitlint --from HEAD~1 --to HEAD --verbose
  lint:
    desc: run linters on Helm chart
    cmds:
      - helm lint $CHART_PATH
      - helm template $CHART_PATH | kubeval
  docs:
    desc: renders docs
    cmds:
      - helm-docs $CHART_PATH && cp $CHART_PATH/README.md .
  test:
    desc: test helm chart
    cmds:
      - cd tests && go test ./...
  test.integration:
    desc: test helm chart with integrations tests
    cmds:
      - cd tests && go test --tags=integration
  package:
    desc: package helm chart
    cmds:
      #- rm -rf .cr-release-packages/
      #- git checkout master
      #- cr package $CHART_PATH
      - helm package query-exporter/ --destination build/
      # TODO: - cr package $CHART_PATH --sign
  upload:
    desc: upload packaged helm chart to github repository releases page
    cmds:
      - git checkout master
      - cr upload -o curuvija --git-repo $GITHUB_REPO --package-path .cr-release-packages/ --token $GH_TOKEN --release-notes-file CHANGELOG.md
      - cr upload -o curuvija --git-repo helm-charts --package-path .cr-release-packages/ --token $GH_TOKEN --release-notes-file CHANGELOG.md
  release:
    desc: release helm chart manually
    cmds:
      - task: lint
      - task: templates
      - task: docs
      - task: test
      - task: infer
      - task: state
      - task: make
      - task: package
      - task: mark
      - task: publish
      - task: upload
  templates:
    desc: renders templates into folder
    cmds:
      - helm template default query-exporter/ > tests/rendered_templates/default.yaml
  infer:
    desc: nyx summary
    cmds:
      - nyx --summary infer
      - nyx infer --summary-file=build/nyx_summary
      #- docker run -it --rm -v .:/project mooltiverse/nyx:latest --summary infer
  mark:
    desc: mark nyx
    cmds:
      - nyx mark
  make:
    desc: make nyx
    cmds:
      - nyx make
      - task: appVersion
  publish:
    desc: publish nyx
    cmds:
      - nyx publish
  state:
    desc: build nyx state file
    cmds:
      - nyx --state-file=build/nyx-state.json infer
  appVersion:
    desc: replaces appVersion in Helm chart
    cmds:
      - export APP_VERSION=$(cat query-exporter/values.yaml | yq .image.tag) && yq e -i '.appVersion = env(APP_VERSION)' query-exporter/Chart.yaml
