version: '3'

env:
  CHART_NAME: query-exporter
  CHART_PATH: query-exporter
  GITHUB_REPO: query-exporter

tasks:
  commitlint:
    desc: run commitlint
    cmds:
      - npx commitlint --from HEAD~1 --to HEAD --verbose
  lint:
    desc: run linters on Helm chart
    cmds:
      - helm lint $CHART_PATH
      #- helm template $CHART_PATH | kubeval # TODO: fix query-exporter/templates/servicemonitor.yaml: Failed initializing schema https://kubernetesjsonschema.dev/master-standalone/servicemonitor-monitoring-v1.json: Could not read schema from HTTP, response status is 40
  docs:
    desc: renders docs
    cmds:
      - helm-docs $CHART_PATH && cp $CHART_PATH/README.md .
  test:
    desc: test helm chart
    cmds:
      - cd tests && go test ./...
  test.integration:
    desc: test helm chart with integrations tests
    cmds:
      - cd tests && go test --tags=integration
  package:
    desc: package helm chart
    cmds:
      #- rm -rf .cr-release-packages/
      #- git checkout master
      #- cr package $CHART_PATH
      - helm package query-exporter/ --destination build/ --destination .cr-release-packages/
      # TODO: - cr package $CHART_PATH --sign
  upload:
    desc: upload packaged helm chart to github repository releases page
    cmds:
      #- git checkout master
      #- cr upload -o curuvija --git-repo $GITHUB_REPO --package-path .cr-release-packages/ --token $GH_TOKEN --release-notes-file CHANGELOG.md # TODO: this is done by nyx, remove it
      #- cr upload -o curuvija --git-repo helm-charts --package-path .cr-release-packages/ --token $HELM_CHARTS_TOKEN --release-notes-file CHANGELOG.md # TODO: generate new token for helm-charts repo
      # TODO: check if in nyx you can pulish to another destination (check git remotes https://mooltiverse.github.io/nyx/guide/user/configuration-reference/git/#remote-definition)
      # TODO: this one is executed after you upload helm chart to helm-charts repo
      #- cr index --index-path .cr-release-packages/index.yaml --package-path .cr-release-packages/ --owner curuvija --git-repo helm-charts --pr --token $HELM_CHARTS_TOKEN
      # TODO: https://github.com/isac322/static-lb/blob/7d694583ed29d475cd195e5766335b5308c5bdfa/.github/workflows/release-charts.yaml and https://github.com/helm/chart-releaser-action/issues/22
      - cd ../helm-charts
      - cr index --index-path index.yaml --package-path ../query-exporter/.cr-release-packages/ --owner curuvija --git-repo helm-charts --pr --token $HELM_CHARTS_TOKEN
  release:
    desc: release helm chart manually
    cmds:
      #- task: lint
      - task: commitlint
      - task: cleanup
      - task: templates
      - task: docs
      #- task: test
      - task: infer
      #- task: state
      - task: make
      - task: package
      - task: mark
      - task: publish
  templates:
    desc: renders templates into folder
    cmds:
      - helm template default query-exporter/ > tests/rendered_templates/default.yaml
  infer:
    desc: nyx summary
    cmds:
      - nyx infer --summary-file=build/nyx_summary
      #- docker run -it --rm -v .:/project mooltiverse/nyx:latest --summary infer
  mark:
    desc: mark nyx
    cmds:
      - nyx mark
  make:
    desc: make nyx
    cmds:
      - nyx make
      - task: appVersion
  publish:
    desc: publish nyx
    cmds:
      - nyx publish
      - gh repo clone curuvija/helm-charts build/helm-charts
      - |
        cd build/helm-charts
        cr upload --config ../../cr.yaml --token $HELM_CHARTS_GH_TOKEN
        cr index --config ../../cr.yaml --token $HELM_CHARTS_GH_TOKEN
      #- cr upload -o curuvija --git-repo helm-charts --package-path ../../.cr-release-packages --token $HELM_CHARTS_TOKEN --release-notes-file CHANGELOG.md
      #- cr index --index-path index.yaml --package-path ../../.cr-release-packages/ --owner curuvija --git-repo helm-charts --pr --token $HELM_CHARTS_TOKEN
  appVersion:
    desc: replaces appVersion in Helm chart
    cmds:
      - export APP_VERSION=$(cat query-exporter/values.yaml | yq .image.tag) && yq e -i '.appVersion = env(APP_VERSION)' query-exporter/Chart.yaml
  cleanup:
    desc: run cleanup job
    cmds:
      - rm -rf build