version: '3'

env:
  CHART_NAME: query-exporter
  CHART_PATH: query-exporter
  GITHUB_REPO: query-exporter

tasks:
  kube-linter:
    desc: run kube-linter
    cmds:
      - helm template query-exporter/ | kube-linter lint -
  kube-score:
    desc: Run kube-score on rendered files
    cmds:
      - helm template query-exporter/ | kube-score score -
  kubeconform:
    desc: run kubeconform on rendered templates
    cmds:
      - helm template query-exporter/ | kubeconform -ignore-missing-schemas -summary -
  kubeval:
    desc: run kubeval on rendered templates
    cmds:
      - helm template query-exporter/ | kubeval -
  datree:
    desc: run datree
    cmds:
      - datree config set offline local
      - helm template query-exporter/ | datree test -
  polaris:
    desc: run polaris agains helm chart
    cmds:
      - polaris audit --helm-chart query-exporter --helm-values query-exporter/values.yaml --only-show-failed-tests --format=pretty
  trivy:
    desc: run trivy against helm chart
    cmds:
      - trivy config query-exporter/
  lint:
    desc: run linters on Helm chart
    cmds:
      - helm lint $CHART_PATH
      - helm template $CHART_PATH | kubeval
  kics:
    desc: run kics on helm chart
    cmds:
      - docker pull checkmarx/kics:latest
      - docker run -t -v .:/path checkmarx/kics scan -p /path/query-exporter
  checkov:
    desc: run checkouv on helm chart
    cmds:
      - docker run -t -v .:/path bridgecrew/checkov -d /path/query-exporter
  docs:
    desc: renders docs
    cmds:
      - helm-docs $CHART_PATH && cp $CHART_PATH/README.md .
  tests:
    desc: test helm chart
    cmds:
      - cd tests && go test ./...
  tests.integration:
    desc: test helm chart with integrations tests
    cmds:
      - cd tests && go test --tags=integration
  package:
    desc: package helm chart
    cmds:
      - rm -rf .cr-release-packages/
      - git checkout master
      - cr package $CHART_PATH
  upload:
    desc: upload packaged helm chart to github repository releases page
    cmds:
      - git checkout master
      - cr upload -o curuvija --git-repo $GITHUB_REPO --package-path .cr-release-packages/ --token $GITHUB_TOKEN --release-notes-file CHANGELOG.md
      - cr upload -o curuvija --git-repo helm-charts --package-path .cr-release-packages/ --token $GITHUB_TOKEN --release-notes-file CHANGELOG.md
      - rm .cr-release-packages/*
  release:
    desc: release helm chart manually
    cmds:
      - task: lint
      - task: templates
      - task: docs
      - task: test
      - task: package
      - task: upload
  templates:
    desc: renders templates into folder
    cmds:
      - helm template default query-exporter/ > tests/rendered_templates/default.yaml
