version: '3'

env:
  CHART_NAME: query-exporter
  CHART_PATH: query-exporter
  GITHUB_REPO: query-exporter

tasks:
  lint:
    desc: run linters on Helm chart
    cmds:
      - helm lint $CHART_PATH
      - helm template $CHART_PATH | kubeval
  docs:
    desc: renders docs
    cmds:
      - helm-docs $CHART_PATH && cp $CHART_PATH/README.md .
  tests:
    desc: test helm chart
    cmds:
      - cd tests && go test ./...
  tests.integration:
    desc: test helm chart
    cmds:
      - cd tests && go test --tags=integration
  package:
    desc: package helm chart
    cmds:
      - rm -rf .cr-release-packages/
      - git checkout master
      - cr package $CHART_PATH
  upload:
    desc: upload packaged helm chart to github repository releases page
    cmds:
      - git checkout master
      - cr upload -o curuvija --git-repo $GITHUB_REPO --package-path .cr-release-packages/ --token $GITHUB_TOKEN --release-notes-file CHANGELOG.md
      - cr upload -o curuvija --git-repo helm-charts --package-path .cr-release-packages/ --token $GITHUB_TOKEN --release-notes-file CHANGELOG.md
  release:
    desc: release helm chart manually
    cmds:
      - task: lint
      - task: docs
      - task: test
      - task: package
      - task: upload
  templates:
    desc: renders templates into folder
    cmds:
      - helm template default query-exporter/ > tests/rendered_templates/default.yaml
