apiVersion: v2
name: query-exporter
version: 1.0.0
description: A Helm chart for query-exporter (export Prometheus metrics from SQL queries)
maintainers:
  - name: 'Milos Curuvija'
    email: 'curuvija@live.com'

type: application
appVersion: "2.8.3"
