name: Release Helm chart
run-name: ${{ github.actor }} is relasing new helm chart

# kind cluster create https://github.com/marketplace/actions/kind-cluster and https://github.com/marketplace/actions/helm-chart-testing
# chart-releaser-action https://github.com/helm/chart-releaser-action

on: [push, pull_request]
# on:
#   push:
#     branches:
#       - master

env:
  CHART_NAME: query-exporter
  CHART_PATH: query-exporter
  GITHUB_REPO: query-exporter

jobs:
  pre:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: List files in the repository
        run: |
          ls -la ${{ github.workspace }}
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install node packages
        run: npm install
      - name: Check with commitlint
        run: npx commitlint --from HEAD~1 --to HEAD --verbose
      - uses: azure/setup-helm@v4.2.0
        id: install
      - name: Generate helm chart templates
        run: helm template default query-exporter/ > tests/rendered_templates/default.yaml
        # this one fails when you use act on it, disable it if you test it locally and uncomment it when you're done and ready to push
      - name: Generate helm docs 
        uses: losisin/helm-docs-github-action@v1
        with:
          chart-search-root: "query-exporter"
          output-file: "README.md"
          git-push: false
          git-push-user-name: "Milos Curuvija"
          git-push-user-email: "curuvija@live.com"
          git-commit-message: "chore: update Helm documentation"
      - name: Run nyx Infer
        uses: mooltiverse/nyx-github-action@main
        with:
          command: infer
          resume: true
      - name: Configure app version in Chart.yaml
        uses: mikefarah/yq@master
        with:
          cmd: export APP_VERSION=$(cat query-exporter/values.yaml | yq .image.tag) && yq e -i '.appVersion = env(APP_VERSION)' query-exporter/Chart.yaml
      - name: Run nyx make
        uses: mooltiverse/nyx-github-action@main
        with:
          command: make
          resume: true
      - name: Package helm chart
        run: helm package query-exporter/ --destination build/ --destination .cr-release-packages/
      - name: Run nyx mark
        uses: mooltiverse/nyx-github-action@main
        with:
          command: mark
          resume: true
      - name: Run nyx publish
        uses: mooltiverse/nyx-github-action@main
        with:
          command: publish
          resume: true
      # - name: Clone Helm charts repo
      #   run: gh repo clone curuvija/helm-charts build/helm-charts
      #   env:
      #     GH_TOKEN: ${{ secrets.HELM_CHARTS_GH_TOKEN }}
      - name: Check out helm-charts repository code
        uses: actions/checkout@v3
        with:
          repository: 'curuvija/helm-charts'
          path: 'build'
          token: ${{ secrets.HELM_CHARTS_GH_TOKEN }}
          fetch-depth: 0
      # check for more details https://github.com/helm/chart-releaser/blob/main/README.md
      # and https://github.com/helm/chart-releaser-action
      - name: Go to build directory
        run: cd build/helm-charts
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: .cr-release-packages/
          config: cr.yaml
        env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          HELM_CHARTS_GH_TOKEN: "${{ secrets.HELM_CHARTS_GH_TOKEN }}"