# name: Release Helm chart
# run-name: ${{ github.actor }} is relasing new helm chart

# # kind cluster create https://github.com/marketplace/actions/kind-cluster and https://github.com/marketplace/actions/helm-chart-testing
# # chart-releaser-action https://github.com/helm/chart-releaser-action

# on:
#   push:
#     branches:
#       - master

# jobs:
#   release:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Check out repository code
#         uses: actions/checkout@v3
#         with:
#           fetch-depth: 0
#       - name: List files in the repository
#         run: |
#           ls ${{ github.workspace }}
#       # - name: Configure Git
#       #   run: |
#       #     git config user.name "$GITHUB_ACTOR"
#       #     git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
#       - name: Git checkout
#         uses: actions/checkout@v3
#         with:
#           fetch-depth: 0
#       - name: Run nyx Infer
#         uses: mooltiverse/nyx-github-action@main
#         with:
#           command: infer
#           resume: true
#           stateFile: .nyx-state.json
#       # Run other tasks here....
#       - name: Run nyx Publish
#         uses: mooltiverse/nyx-github-action@main
#         env:
#           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         with:
#           command: publish
#           resume: true
#           stateFile: .nyx-state.json