name: Create Release

on:
  push:
    tags:
      - '*.*.*'
  pull_request:

jobs:
  changelog:
    name: Changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Extract release notes
        id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v2
        with:
            changelog_file: CHANGELOG.md
#   release:
#     needs: changelog
#     name: Create release
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4
#       - name: Extract release notes
#         id: extract-release-notes
#         uses: ffurrer2/extract-release-notes@v2
#       - name: Create release
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         run: gh release create --notes '${{ steps.extract-release-notes.outputs.release_notes }}' --title ${{ github.ref_name }} ${{ github.ref_name }}